import { StyleSheet, Platform, StatusBar } from "react-native";
import {
  widthPercentageToDP as wp,
  heightPercentageToDP as hp,
} from "react-native-responsive-screen";
export const styles = StyleSheet.create({
  container: {
    flex: 1,
    paddingTop: Platform.OS === "android" ? StatusBar.currentHeight : 0,
  },
  header: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
  },
  backButtons: {
    paddingTop: 36,
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    width: "100%",
    position: "absolute",
    paddingInline: 20,
  },
  button: {
    padding: 16,
    backgroundColor: "#ffffff99",
    borderRadius: 9999,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 20,
  },
  recipeDetails: {
    marginTop: 20,
    paddingTop: 16,
    paddingBottom: 20,
    borderTopWidth: 1,
    borderColor: "#E6E6E6",
    marginInline: 20,
  },
  recipeName: {
    fontSize: hp(3),
    fontWeight: "bold",
    marginBottom: 13,
  },
  typeWrapper: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 13,
  },
  recipeCategory: {
    fontSize: hp(2),
    color: "#6B7280",
  },
  recipeArea: {
    fontSize: hp(1.5),
    color: "#ffffff",
    backgroundColor: "#F50B0B90",
    borderRadius: 555,
    paddingHorizontal: 10,
    paddingVertical: 2,
    marginLeft: 5,
  },
  miscWrapper: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-around",
    marginBottom: 29,
    marginTop: 15,
  },
  miscInside: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    padding: 10,
    borderRadius: 555,
    backgroundColor: "#F50B0B",
  },
  iconWrapper: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    width: 50,
    height: 50,
    backgroundColor: "#ffffff",
    borderRadius: 9999,
  },
  timeWrapper: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    marginTop: 10,
  },
  minutes: {
    fontSize: hp(2.2),
    fontWeight: "500",
    color: "#ffffff",
    marginBottom: 3,
  },
  minutesText: {
    fontSize: hp(1.5),
    fontWeight: "700",
    color: "#ffffff",
    marginBottom: 5,
  },
  title: {
    fontSize: hp(2.5),
    fontWeight: "bold",
    marginBottom: 10,
  },
  ingredientsList: {
    marginTop: 10,
    marginLeft: 10,
    display: "flex",
    gap: 15,
  },
  ingredientsListWrapper: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
  },
  dots: {
    width: hp(1.7),
    height: hp(1.7),
    backgroundColor: "#F50B0B",
    borderRadius: 9999,
    marginHorizontal: 5,
  },
  ingredientsLisDetails: {
    display: "flex",
    flexDirection: "row",
    gap: 5,
  },

  measure: {
    fontSize: hp(1.7),
    fontWeight: "900",
    color: "#525252",
  },
  ingredient: { fontSize: hp(1.7), fontWeight: "500", color: "#525252" },
  ingredientsContainer: {
    marginBottom: 20,
    paddingBottom: 20,
    borderBottomWidth: 1,
    borderColor: "#E6E6E6",
  },
  instructionsText: {
    fontSize: hp(1.7),
    fontWeight: "500",
    color: "#525252",
    lineHeight: 24,
    textAlign: "justify",
  },
});
